services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:latest
    volumes:
      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
    ports:
    - "5672:5672"
  redis:
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CELERY_DB_INDEX=10
      - REDIS_STORE_DB_INDEX=0
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_PORT=5672
      - APP_BROKER_URI=amqp://rabbitmq
      - APP_BACKEND_URI=redis://redis
      - GCS_CREDS_PATH=_gcs_creds.json
      - GCS_BUCKET_NAME=test-data-01
      - GC_PROJECT_ID=som-htdatalab
    depends_on:
      - rabbitmq
      - redis
